### ISSUE TITLE
:error_no_group when function is called from a separate app

### ISSUE THREAD

**Issue by churcho** [epgsql/pooler#73] opened 2017-02-10 10:14 UTC
I keep getting 
```
** (exit) exited in: :gen_server.call({:error_no_group, :riak})
** (EXIT) no connection to riak
```

I have an app_users and app_db and app_api, my tests in app_users are running fine but if I have a test in app_api that calls app_users code I get a no connection to riak. app_db is the only interface to riak and app_users has a dependency to it and app_api has a dependency to app_users. The only app with pooler in the deps setting is app_db which handles connection pooling to the database.

What am I mixing up?

**Comment by churcho** [comment] 2017-02-10 12:30
I managed to get rid of the error by applying app_db as an application dependency on app_api. Doesn't look clean to me because I don't want the api to be app_db aware

**Comment by nav301186** [comment] 2017-03-01 16:33
I am also getting same error, I am trying to use Elixir Riak client in an umbrella app.

**Comment by seriyps** [comment] 2023-04-09 00:53
Very difficult to understand what exactly the problem is. I'm closing it for now as outdated, but feel free to reopen if disagree.

**Closed by seriyps** 2023-04-09 00:53 UTC
